WordCounter.Web/Models/ErrorViewModel.cs
using System;

namespace WordCounter.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WordCounter.Web/Controllers/WordController.cs
using Microsoft.AspNetCore.Mvc;
using WordCounter.Tools.Interface;


namespace WordCounter.Web.Controllers
{
    public class WordController : Controller
    {
        private readonly IWordProcess _wordProcess;

        public WordController(IWordProcess wordProcess)
        {
            _wordProcess = wordProcess;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(bool dataRefresh = false) //datarefresh is for caching parameter
        {
            var model = _wordProcess.GetTopXListOfWord(10, "..//WordCounter.ConsoleApp/ResultXmls/words.xml", dataRefresh);
            return View(model);
        }
    }
}

WordCounter.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WordCounter</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Word" asp-action="Index" class="navbar-brand">WordCounter</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Word" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WordCounter, Prepared by <em><a href="https://gitlab.com/codefx">Codefx</a></em></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WordCounter.Web/Views/Word/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-md-10 text-center">
        <br/><br/><h3>Welcome to the Word Frequency count list ! If you wish to see the list, push the button</h3><br/>
        <a href="/Word/List" class="btn btn-success text-center ">Get List</a>
    </div>
</div>

WordCounter.Web/Views/Word/List.cshtml
@model IEnumerable<WordCounter.Tools.Model.Word>

@{
    ViewData["Title"] = "List";
}
<h3><i>Welcome to Word Frequency  List</i></h3>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Count)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Count)
                </td>
            </tr>
        }
    </tbody>
</table>
    <a href="List?dataRefresh=true" class="btn btn-danger">Refresh Cache Data</a>